version: '3.9'

volumes:
  elasticsearch_data: {}
  files_data: {}

services:
  nginx:
    build:
      context: .
      dockerfile: ./compose/nginx/Dockerfile
    ports:
      - "8888:80"
    depends_on:
      - server
    volumes:
      - files_data:/usr/share/nginx/html/files
    environment:
      PUBLIC_URL: /ocr/
      REACT_APP_API_URL: ./api/
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: ../compose/server/Dockerfile
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_DEBUG: 1
      ES_URL: http://elasticsearch:9200
    ports:
      - "5001:5001"
    depends_on:
      elasticsearch:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - files_data:/app/files
    restart: unless-stopped

  elasticsearch:
    build:
      context: ./compose/elasticsearch
      dockerfile: Dockerfile
    ports:
     - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      xpack.security.enabled: false
      discovery.type: single-node
    healthcheck:
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:9200
      interval: 10s
      timeout: 30s
      retries: 15
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 15
      start_period: 10s
    volumes:
      - files_data:/app/files
    restart: unless-stopped

  celery_worker:
    build:
      context: ./server
      dockerfile: ../compose/celery/Dockerfile
    command: celery -A celery_app.celery worker --loglevel=info --concurrency=12
    volumes:
      - files_data:/app/files
    links:
      - redis
    depends_on:
      - redis
    restart: unless-stopped